### ISSUE TITLE
Added Intermediate Scenario for the Current Scenario

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#106]
for example when i have created fixtures and parts and I am trying to teach the program to pick and place. I should be able to press a button go back to original setup and run the program again. else as of now i have to edit the part again and again.

**Comment by neoaero99** [comment]
Now a separate instance of the scenario is loaded, so by pressing load in the scenario window, you can revert to the last instance of the active scenario that was saved.

**Comment by neoaero99** [comment]
Though bear in mind, if you load another scenario before saving, any changes made to the current scenario are lost.
