### ISSUE TITLE
issue with programming points wrt to user frame

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#118]
When we record a point in the program by default the point is with respect to user frame. if there is not user frame then it assumes its coordinates with respect to world frame.

Now if I have created a user frame using 4 point method and recorded a point in the program.
next i go back to frames and record a new point for the origin in the user frame.
now when i go back and run the program, the robot should move to a point with respect to this new origin.
Also if i re record all the points of the user frame then the robot should move to a position wrt to this new frame created.

**Comment by spsid13** [comment]
Also if i re record all the points of the user frame then the robot should move to a position wrt to this new frame created.

**Comment by neoaero99** [comment]
What exaclty are you having trouble with?

**Comment by neoaero99** [comment]
Points recorded in a program do change with respect of the User frame. Though, there are still issues with converting between frames: see #116
