### ISSUE TITLE
register instructions

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#125]
step 1  I record a new point L p[1] 100% fine
step 2 I want to edit the P[1] and change it to Pr[3]
When I select the global register it does nothing..

**Comment by neoaero99** [comment]
Have you inputted a value for Pr[3]?

**Comment by neoaero99** [comment]
In other words, is Pr[3] already defined?

**Comment by spsid13** [comment]
Ohh no. 

Get Outlook for iOS

On Tue, Oct 11, 2016 at 1:48 PM -0400, "Neo Aero" notifications@github.com wrote:

In other words, is Pr[3] already defined?

**Comment by neoaero99** [comment]
You cannot specify a position register that is uninitialized.

**Comment by spsid13** [comment]
I should be able to specify it but the program should give an error. Otherwise those registers become useless since they cannot be used as variables in register equations.

Get Outlook for iOS

On Tue, Oct 11, 2016 at 1:55 PM -0400, "Neo Aero" notifications@github.com wrote:

You cannot specify a position register that is uninitialized.

**Comment by neoaero99** [comment]
You can specify empty registers in register statements, you simply cannot specify empty position registers for motion instructions.

**Comment by neoaero99** [comment]
You can now specific uninitialized global registers for motion instructions.
