### ISSUE TITLE
Add end effector offset

### ISSUE THREAD

**Issue by skuhl** [skuhl/RobotRun#13]
I seem to recall Alex or someone mentioning that we will need to adjust the actual location of the end effector based on the effector that is attached to the robot. It sounded like this should be configurable by the user. We need to collect more information and figure out exactly how this works and maybe consider drawing a little red dot where the actual end effector supposedly is so people can see the offset.

**Comment by neoaero99** [comment]
The end effector offset exists, I'll be that the Tool Frame Three Point method still needs work.
