### ISSUE TITLE
Delete Option Removes Everything

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#136]
Every time I try to delete a single line from a program, all the instructions in the program are deleted instead.

**Comment by neoaero99** [comment]
So, I believe the problem is actually that selecting a line to delete removes all lines below the selected line as well as the selected line.

**Comment by vtdrusch** [comment]
I see the problem, deletion now works as intended.

**Comment by neoaero99** [comment]
It still doesn't work
