### ISSUE TITLE
The second robot is getting lost in the camera view

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#139]
![ggt](https://cloud.githubusercontent.com/assets/17214301/23336505/299ce5e8-fba0-11e6-9819-07124d97c316.PNG)

**Comment by neoaero99** [comment]
Yeah, I figured I would have to fix the camera soon or later.

**Comment by neoaero99** [comment]
I managed to extend the camera view, so the robot should no longer be clipped by the camera. However, if you move world objects too far away from robots, then they will be clipped by the camera.
