### ISSUE TITLE
unable to save scenario

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#144]
I created a scenario called gg..
then clicked on load
then created a fixture
pressed cntrl+s to save
then went on scenario tab clicked on save
then again selected the scenario gg and pressed load
my fixture does not load..

**Comment by neoaero99** [comment]
I managed to fix scenario saving. Also, there is an undo feature now to replace my sketchy saving method for scenarios. You can undo up to the past ten edits or deletes for the current active scenario with the u key.

**Comment by spsid13** [comment]
Great thanks josh

Get Outlook for iOS




On Sun, Mar 19, 2017 at 8:58 PM -0400, "Joshua Hooker" <notifications@github.com> wrote:












I managed to fix scenario saving. Also, there is an undo feature now to replace my sketchy saving method for scenarios. You can undo up to the past ten edits or deletes for the current active scenario with the u key.
