### ISSUE TITLE
should be able to edit the values of a recorded point

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#152]

**Comment by neoaero99** [comment]
Do you mean recorded points for motion instructions?

**Comment by spsid13** [comment]
Yes

Get Outlook for iOS




On Sat, Mar 25, 2017 at 9:59 AM -0400, "Joshua Hooker" <notifications@github.com> wrote:












Do you mean recorded points for motion instructions?

**Comment by neoaero99** [comment]
Already an issue, see #111

**Comment by spsid13** [comment]
Ohh sorry. But it's important that we resolve this one :)

Get Outlook for iOS




On Sat, Mar 25, 2017 at 10:09 AM -0400, "Joshua Hooker" <notifications@github.com> wrote:












Already an issue, see #111

**Comment by neoaero99** [comment]
That is alright, I forgot that we even had an issue for it until now.
