### ISSUE TITLE
Draw a coordinate system

### ISSUE THREAD

**Issue by skuhl** [skuhl/RobotRun#16]
We should draw a coordinate system on the "ground". I.e., draw a textured quad or draw a bunch of lines to form a grid. The end effector position could be projected down onto that grid---making it easier for people to see where the end effector is.

**Comment by neoaero99** [comment]
So, I can get it to draw a grid (though it looks a bit weird depending on the angle), but I am having trouble drawing a line between the ground plane and the robot's end effector
