### ISSUE TITLE
Previous Line Memory for Program Instruction Navigation

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#161]
So you press F2(new inst) and then select IO[suction] = off
the cursor on the programming window goes to the first line.
it should automatically go to the current line.

**Comment by neoaero99** [comment]
Once an operation (i.e. adding a new instruction, point, or editing an instruction, deleting lines, etc.) has been completed in a program's instruction navaigation screen, then the program should return to the line that was active before the operation was performed (see Siddharth's comment above).
