### ISSUE TITLE
Continuous Motion Glitch

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#165]
When runnning through many motion instructions, the robot arm may glitch and the software can begin to consume a large amount of the CPUs resources (core procssing power and memory).

**Comment by vtdrusch** [comment]
I tested this issue again by running a program on loop for a good 30 minutes and didn't notice any problems, so I'm going to close this issue for now. I monitored memory use during this test and didn't notice a correlation between that and execution time, but I did notice that our program seems to hover at around 1GB, so it might be worth publishing some recommended/ minimum operating specs for host computers.
