### ISSUE TITLE
circular instruction problem

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#168]
so lets say 
I record starting point
L P1 500mm/s fine
then i go to intermediate
C P2 500mm/s Fine
then i record final point
  :P3 500mm/s Fine
When I record the next point which is supposed to be
L P4 500mm/s fine   instead it labels it as P3 and records new location to P3

**Comment by spsid13** [comment]
Also when you go to : P3 500mm/s and try to click shift + new pt it changes the label of P3 instead of updating it.

**Comment by neoaero99** [comment]
Fixed this issue too.
