### ISSUE TITLE
Register Expression P[x, y] Insertion Menu Display Glitch

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#172]
![file-2](https://cloud.githubusercontent.com/assets/17214301/25767832/d710a92a-31ca-11e7-9ff0-3703d6a2eee7.jpeg)

**Comment by spsid13** [comment]
it worked fine.

**Comment by neoaero99** [comment]
After replicating Siddharth's issue, I have found that the menu functions fine. So, you can still input the two integer values for x and y.

However, the prompt line, in options, is not rendered on the pendant. I checked the options menu and found that the prompt line exists in the MenuScroll, but is still not rendered on the pendant.

In addition, if you edit a P[x, y] expression element with F4, the prompt line renders displays normally.
