### ISSUE TITLE
Trace function

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#174]
The user should be able to generate a trace of the active robot's end effector position, while the robot is moving. The user should also be able to set the trace on or off.

**Comment by vtdrusch** [comment]
Internal code for creating a trace line when moving the robot is working, now just need a menu button and/or instruction to toggle the trace generation on/ off.

**Comment by neoaero99** [comment]
Trace functionality can be toggled in the miscellanous menu now.
