### ISSUE TITLE
the values in the left side of image do no correspond to the axis shown on the right

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#181]
when I enter the value to move in the x position which coordinate system is it considering? I feel it should consider its own coordinate system that is highlighted so that its easier for user to enter the position values.
![capture](https://cloud.githubusercontent.com/assets/17214301/26523917/7bc379b6-42f1-11e7-9331-036e8f4a0502.JPG)

**Comment by neoaero99** [comment]
There is already an issue for this #156
