### ISSUE TITLE
Offset instruction menu streamlining

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#183]

**Comment by vtdrusch** [comment]
Currently, the process to enable offsets for motion instructions is to highlight the third column of a motion instruction (P[ / RP[), press F5 ([Reg]), and then press F5 again ([Offset]). The offset function should be working, but the process to enable it could use some simplification; we'll look into that.

**Comment by vtdrusch** [comment]
I did have to make minor corrections to the joint-mode offset motion, as well as fix an issue where the user was unable to select the first offset register when adding an offset. I'll push these updates in a build tonight.

**Comment by neoaero99** [comment]
Offset menu interactions now resemble that of a motion instructions position.
