### ISSUE TITLE
the EE button is missing

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#185]
Hi guys,
The EE button is missing coulf you fix it and let me know

**Comment by neoaero99** [comment]
I know, I removed it. You can switch the end effector with Ctrl+E or go to the miscellanous menu and select it with the dropdown

**Comment by neoaero99** [comment]
I am sorry, I forgot that Vincent pushed a new build, so I should have told you, Siddharth.

**Comment by spsid13** [comment]
ok cool
