### ISSUE TITLE
Modify equality and inequality operators to work with boolean operands?

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#191]
The evaluation of IO register in if statements is non-functional. I tried a simple expression:

IO[4] = IO[3]

however, the if statement failed to evaluate.

**Comment by vtdrusch** [comment]
The equality operator (==) is meant to test the equality of floating point operands only, and so using boolean IO operands causes an evaluation error. I could extend the equality and inequality (!=) operators to test for boolean equality, but the preferred way of doing this currently is by using the logical AND (&&), OR (| |) and NOT (!) operators.

**Comment by neoaero99** [comment]
The expression for my example has a size of one. It does not use the equals operator. The equals is the one pertaining the result element

**Comment by neoaero99** [comment]
Never mind that last comment.

**Comment by neoaero99** [comment]
And I see what you mean. That makes sense.
