### ISSUE TITLE
PR[x, y] Operand Multiple Column Edit

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#195]
If you create an expression
PR[2,2] = Pr[2,**2**] + 50
the point index on the right expression cannot be edited directly.
If you press edit you have to enter the register index first and then point index even if the cursor is on the point index.
but for expression on the left it works fine. so try to implement the same function on the right.

**Comment by neoaero99** [comment]
Vincent has added this functionality in the most recent release.
