### ISSUE TITLE
Initialize a position register to 0

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#202]
So, If I have recorded a Position register and I go to edit the register position values X,Y,Z,W,P,R  
then we can give an option to just make all these values zero by pressing F3.

**Comment by neoaero99** [comment]
F1 already clears a register, however, it uninitializes the register as well. I can replace that functionality with the reset functionality. However, F3 already has two functions, so I would have to put it on a different function button.

**Comment by spsid13** [comment]
When you go into EDIT then none of the F keys have anything assigned

**Comment by neoaero99** [comment]
Oh, you mean in the edit menu, ok

**Comment by neoaero99** [comment]
The reset function has been added in the limbo branch
