### ISSUE TITLE
Delete is still not friendly

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#204]
So we should also have something talking about deleting multiple lines press shift + enter
Now here's the thing If I want to delete lines 1-5
I press enter while the cursor is on line 1
then I go down to line 5 and now press Shift and enter
It does not delete all 5 lines. Not sure why.

**Comment by neoaero99** [comment]
So, I want to get this whole shift select thing straight.

If you press shift and enter on a line select menu, then all elements between the last element you selected and the current element you selected should be selected/unselected.

Is that correct?

**Comment by neoaero99** [comment]
I have added in a shift + enter functionality for line select menus like the delete option menu (for some reason the origin shift + enter functionality that Vincent made has been lost).

How it works is that, when you press enter, while shift is on, all lines from the last line you selected to the current line you selected are selected/unselected.

**Comment by neoaero99** [comment]
Although, this functionality is not on the master branch, so until Vincent and I have tested the screens more on our development branch, you will not see this change in a release.

**Comment by vtdrusch** [comment]
I have fixed my implementation of multiple line selection with the shift key, which you will find in the most recent build. Let me know if there are any changes or improvements that need to be made to this feature.
