### ISSUE TITLE
I think we need a small addition for the IF statement

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#212]
We need the AND and OR statements to be implemented. Let me know how difficult this is and how long will it take?

![capture](https://user-images.githubusercontent.com/17214301/27593198-87e7fec4-5b24-11e7-8430-3975725edc61.JPG)

**Comment by neoaero99** [comment]
Currently, we do have AND and OR functionality and you can compare two sub-expressions with AND and OR, though, I am not sure if it is fully functional or how buggy it is.

**Comment by spsid13** [comment]
Without it I am forced to create 3 programs for the gluing scenario which is becoming complicated.. If you can get it to work I can finish the whole code in just 20 lines of 1 program...
