### ISSUE TITLE
Textfield Indexing and Highlighting

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#235]
So when you try to edit the values of position of a new object created, by default it has some values 0.000
Now I am unable to use the mouse to highlight all of that text and delete it. It would be very user friendly if this is possible.

**Comment by neoaero99** [comment]
Unfortunately, I have no way to implement position selecting for textfields, due to issues with ControlP5 fonts.

**Comment by neoaero99** [comment]
I somehow found a solution for textfield indexing, so I will now look into textfield highlighting.

**Comment by neoaero99** [comment]
As of the lastest release, text indexing has been corrected and text highlighting functionality for textfields exists.
