### ISSUE TITLE
By default there is some part or fixture in the menu with the name WO.

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#238]
Can we remove it?

**Comment by neoaero99** [comment]
What do you mean? You can have empty scenarios.

**Comment by spsid13** [comment]
If I make any changes to the position values in the image below nothing on the screen changes because there is no such part in the environment. It is there in the software by default but does not physically exist in the environment. Kinda confusing for users.
![image](https://user-images.githubusercontent.com/17214301/29253096-fc990a72-8042-11e7-897d-7087e3368428.png)

**Comment by neoaero99** [comment]
That is not a part nor a fixture: by default if no element is selected in a dropdown list, then the name of the dropdown list is displayed as the label for the dropdown list. That is name of that dropdown list.

**Comment by neoaero99** [comment]
Though, I can add messages for trying to confirm editing when no world object exists.

**Comment by neoaero99** [comment]
Now the edit menu will hide all editing options, when no objcet is selected on both limbo and master branches (a704bee)
