### ISSUE TITLE
unable to copy and paste the IO lines in program

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#244]

**Comment by neoaero99** [comment]
I am not sure if this was an issue, however, on the most recent build I have no trouble copying and pasting IO instructions in a program.

**Comment by neoaero99** [comment]
I have tried multiple cases for copying and pasting I/O instructions, however, I have had no issues, so I will close this issue for now. If the issue comes up again, then please include some more details about the issue.
