### ISSUE TITLE
So the robot is colliding with itself. 

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#245]
I remember, Vince allowed more movement for the J5 axis. We need that range of motion but it shouldn't highlight as colliding with itself.
![image](https://user-images.githubusercontent.com/17214301/29488134-87430518-84d2-11e7-9392-f9bc291367bb.png)

**Comment by neoaero99** [comment]
Why should the collision not be shown? There are few ways, in which the robot can collide with itself. Most of which involve one of the robot's end effectors and one of its segments.

**Comment by neoaero99** [comment]
More importantly, the bounding boxes exist partially to show when objects collide in the scene: this includes the robotic arms. If you have a reason for this, then reopen this issue, so we can discuss it.
