### ISSUE TITLE
Implement additional program instructions

### ISSUE THREAD

**Issue by skuhl** [skuhl/RobotRun#25]

**Comment by neoaero99** [comment]
I would like to meet with Siddharth to discuss how conditionals are handled with the FANUC robots.

**Comment by neoaero99** [comment]
Siddharth also mentioned that Copy+Paste functions should exist for program statements.

**Comment by vtdrusch** [comment]
Altering this issue to encompass the broader range of instruction types that have yet to be implemented. In addition to conditional instructions, we still have control flow and register arithmetic functions to implement, among others.

**Comment by neoaero99** [comment]
Vincent finished this.
