### ISSUE TITLE
Tool Frame 6 point method seems to have been broken.

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#255]
Try to use 6 point method to create a tool frame, Record the Orient Origin, X direction, and Y Direction points. The coordinates created at the tool tip do not match these.

**Comment by neoaero99** [comment]
What do you mean?

**Comment by spsid13** [comment]
The coordinate axis that is visible showing the tool X direction, tool y direction does not match the directions taught.

**Comment by spsid13** [comment]
[tmp.zip](https://github.com/skuhl/RobotRun/files/1237379/tmp.zip)
Use the temp folder and see the first tool frame created.
Use the pointer tool for this frame.

**Comment by spsid13** [comment]
Use the temp folder and see the first tool frame created.

**Comment by spsid13** [comment]
![image](https://user-images.githubusercontent.com/17214301/29498869-57191e76-85d2-11e7-9762-71c1d85c5c7f.png)

**Comment by neoaero99** [comment]
The tool frame 6 point method has been modified to take the robot's current orientation into account when teaching the frame (a3200dc). These changes exist as of the 1.2.4 release.
