### ISSUE TITLE
Intel Graphics 630 OpenGL ES Error

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#256]
![image](https://user-images.githubusercontent.com/17214301/29643878-fe5ca44a-883f-11e7-93e8-550099a232f5.png)

**Comment by neoaero99** [comment]
What OS does your computer have?

**Comment by spsid13** [comment]
windows 10

**Comment by neoaero99** [comment]
I would make sure your video graphics drivers for that computer are up to date.

**Comment by neoaero99** [comment]
What type is your processor (32-bit or 64-bit)?
What key of graphics card do you have?

**Comment by neoaero99** [comment]
I found an [issue](https://github.com/processing/processing/issues/4802) on Processing's Github page that may be relevant.

**Comment by neoaero99** [comment]
This issue seems to be related to the graphics hardware or software. Here is a link to a thread describing a similar problem:
[https://intel-openport-v7.hosted.jivesoftware.com/thread/110921?start=30&tstart=0](https://intel-openport-v7.hosted.jivesoftware.com/thread/110921?start=30&tstart=0)

**Comment by vtdrusch** [comment]
I'm going to close this issue, since I don't think there's anything that can be done on our end to fix it. Make sure your software/ drivers are up to date and if the problem persists, we can try to find a workaround.
