### ISSUE TITLE
Camera Taught Object Preview

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#257]
I taught a grinder part to the camera and the preview was not quite right:
![camera_preview_issue_1](https://user-images.githubusercontent.com/14117158/29775030-b0f63a14-8bd1-11e7-8727-b47c33e90442.png)

I also tried to teach a circsheet part and got a different result:
![camera_preview_issue_2](https://user-images.githubusercontent.com/14117158/29775036-b3d4ff72-8bd1-11e7-9ba0-f987a23f7d0b.png)

Vincent, I merged your recent changes, so I am not sure what the problem is.

**Comment by vtdrusch** [comment]
I found what was causing this issue: a missing pair of parentheses. I've pushed a fix that should repair this scaling issue for camera objects.
