### ISSUE TITLE
Position register record

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#260]
So whenever I try to record a position register, it records the register in JOINT values. 
Let's make Cartesian default because that is used the most.

**Comment by neoaero99** [comment]
It should be recorded based on the robot's active frame

**Comment by spsid13** [comment]
Active frame was world, but it still doesn't work. Even I was surprised because you had it working earlier.

**Comment by neoaero99** [comment]
This issue has been resolved in the master branch.
