### ISSUE TITLE
Make text highlighting more obvious

### ISSUE THREAD

**Issue by skuhl** [skuhl/RobotRun#27]
Right now we highlight text in red. We should maybe highlight the line and then highlight different part of the instructions (if appropriate).

**Comment by neoaero99** [comment]
Despite there being setColorBackground() and setColorForeground() for a textLabel object in the ControlP5 library, neither of those methods seem to change the color of the label. So, the best I can do to highlight a line is highlight all of the test a specific color; would that be alright?

**Comment by skuhl** [comment]
For now, anything that is a step in the right direction is good. We might have to come back and revisit all of the text to make it more legible in general though.

**Comment by neoaero99** [comment]
Vincent has updated the UI to add more obvious highlighting.
