### ISSUE TITLE
Fix World Coordinate Mode Jogging

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#29]
So, I have noticed that when you jog the robot in World Coordinate mode, the motion that the the robot moves does not match the buttons that you press for jogging the robot. Not to mention there is no rotation motion in World mode either.

**Comment by vtdrusch** [comment]
Buttons should correctly correspond to the movement they produce for transnational world coordinate movement.

**Comment by neoaero99** [comment]
This I believe is completed now as well.
