### ISSUE TITLE
Processing 3.1

### ISSUE THREAD

**Issue by vtdrusch** [skuhl/RobotRun#30]
Just a quick announcement: Processing has been updated to version 3.1, and I'd recommend updating just to be on the safe side in ensuring that we don't get any weird problems developing from using disparate versions of the application. The application still runs just fine on either version (the only change to the API being that Processing 3.1 is Java 8+ compliant), I just wanted to double check that everyone is aware of the change.

**Comment by neoaero99** [comment]
Yeah, I updated this morning.

**Comment by vtdrusch** [comment]
Excellent. Hopefully the new version will also solve some of the issues with the editor.

**Comment by neoaero99** [comment]
Yeah ...
