### ISSUE TITLE
Fix circular joint movement

### ISSUE THREAD

**Issue by vtdrusch** [skuhl/RobotRun#31]
The "C" type movement instructions are currently the only instruction type that doesn't seem to function at all. I've fixed a few crashes caused by trying to execute these instructions, but right now they don't appear to do anything other than halt program execution.

**Comment by neoaero99** [comment]
Alright; do you want to reformat the program code first or continue working
on the circular motion?

**Comment by vtdrusch** [comment]
Go ahead and keep doing what you've been doing, I'm going to look at a new
design for the program execution code later today.

**Comment by neoaero99** [comment]
I realized that we need the circular motion to work in order to allow for
the rotational jogging in the World Frame.

**Comment by vtdrusch** [comment]
Circular IK is complete, closing this issue (will still need to update C type instructions, but this is a different problem).
