### ISSUE TITLE
The Robot's Speed

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#37]
When I reviewed the 3-Point method with Siddharth, he mentioned that the Robot should be able to move at speeds slower than our current 1% speed.

**Comment by vtdrusch** [comment]
I've reduced both the robot's translational and rotational base speed by 75%, which seems to have brought the robot's movement more in-line with that of the actual robotic arm's. Users should now be able to control the robot's position in a much more granular way, and we can also add a further step down from 1% speed for fine motor control.

**Comment by vtdrusch** [comment]
Also tweaked the joint motor speed values for joint rotational movements. Interested to see how Alex and Siddharth like these changes.

**Comment by neoaero99** [comment]
Cool, sounds great.
