### ISSUE TITLE
Resizing of the Window

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#45]
So, Siddharth was trying to run the program on a computer with a screen resolution of 1366x768 and it would seem that the size of the window is just too large for his screen. I would recommend that we add functionality to resize the screen for at least the default size and a size manageable for a window of 1366x768.

**Comment by vtdrusch** [comment]
UI and default window size reduced to 720 vertical pixels. Closing this issue for now, we can revisit this if we find the need to further decrease the application window size.
