### ISSUE TITLE
Move to recorded point when creating frame

### ISSUE THREAD

**Issue by vtdrusch** [skuhl/RobotRun#52]
While entering points to construct a user/ tool frame for either the 3, 4, or 6 point entry methods, the user should have the option to reset the robot arm's position and orientation to that of any point that has already been recorded for the construction of the frame.

**Comment by neoaero99** [comment]
As of now, you can move any points taught to the Frame, when teaching a Frame in either 3-Point Method as well as the 4-Point Method or the Six-Point Method.
