### ISSUE TITLE
Fix floating point register input

### ISSUE THREAD

**Issue by vtdrusch** [skuhl/RobotRun#56]
The process of specifying a register value has been observed to be broken in certain circumstances, will have to look into this further.

**Comment by neoaero99** [comment]
How so?

**Comment by vtdrusch** [comment]
When editing a floating point register, a 0.0 will be pre-pended to the
value, making it impossible to create a value of 0.1 or greater.

**Comment by neoaero99** [comment]
Ah, I see the misunderstanding. The backspace key functions for floating point input, so if you wish to remove the 0.0, then you can use the backspace key. I just adding the initialization, because I thought it would be useful. You can initialize it to an empty string if you wish.

**Comment by neoaero99** [comment]
The backspace key works in almost all input fields, at least it should.
