### ISSUE TITLE
pressing shift coordinate shows the current user and tool frame but cannot modify

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#63]
The user should be able to enter the number of frame here. suppose he wants to activate user frame 6 then he should be able to enter 6 when the cursor is on user frame and it should be set

**Comment by neoaero99** [comment]
You can now edit the active Tool and User frame from the Active Frames menu in a similar fashion to inputting a numeric value. Although, you have to either move up or down, or press ENTER to update the current Coordinate System.
