### ISSUE TITLE
world frame tcp position

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#64]
when the end effector is selected and the coordinate is tool frame the rotation is about faceplate center which is the tcp. It should be the same when in world frame as well. Until the tool frame is taught about the end effectors such as vacuum cups center it should consider the tcp to be faceplate..

**Comment by neoaero99** [comment]
I added default Tool Frames for both End Effectors that are set when either one is selected and there is no active Tool Frame. Do you want me to remove it?

**Comment by spsid13** [comment]
In the final software it should be removed. i assume you might now need it for faster testing. Just wanted to highlight it so that we don't forget.

**Comment by neoaero99** [comment]
Alright, will do.

**Comment by neoaero99** [comment]
I removed the default Tool Frames for the End Effectors.
