### ISSUE TITLE
Fixing Position Register Record and Move To Functions

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#73]

**Comment by neoaero99** [comment]
Yeah, I have been having trouble with position registers. Hope to have this fixed by the end of today ...

**Comment by neoaero99** [comment]
I need to change how the position registers are saved and how they are display:

Joint Points are fine, but Cartesian Points need to be saved in reference to the current frame and the joint angles need to be updated when the user uses the Move To function.

**Comment by neoaero99** [comment]
Position Registers are now saved based on the active User frame (if any) and the Move To function for Position registers will treat the position as if it was in the active User frame.
