### ISSUE TITLE
remove serial numbers for registers and position registers

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#74]

**Comment by neoaero99** [comment]
What d o you mean?

**Comment by spsid13** [comment]
The numbers to the left of the register are redundant. Register numbers themselves are enough to identify right?

Get Outlook for iOS

On Mon, Jul 25, 2016 at 8:33 AM -0400, "Neo Aero" notifications@github.com wrote:

What d o you mean?

**Comment by neoaero99** [comment]
Ah, I see what you mean

**Comment by neoaero99** [comment]
Do you want anything else displayed for either of the Register menus?

**Comment by spsid13** [comment]
No. Looks good.

Get Outlook for iOS

On Mon, Jul 25, 2016 at 8:47 AM -0400, "Neo Aero" notifications@github.com wrote:

Do you want anything else displayed for either of the Register menus?

**Comment by neoaero99** [comment]
Alright
