### ISSUE TITLE
Figure out how to load a simple CAD model

### ISSUE THREAD

**Issue by skuhl** [skuhl/RobotRun#8]

**Comment by vtdrusch** [comment]
I haven't examined all the details of the model loading process yet, but from a cursory examination of the system, it looks like model loading should be fairly straightforward for any STL file. I'm going to experiment with an STL model of a cube I found online.

**Comment by vtdrusch** [comment]
I've managed to successfully load a cube model into the program environment. The cube currently is not animated and doesn't interact with the robotic arm at all, but it is apparently loaded and rendered correctly. The next major hurdle here will be implementing some kind of physics properties on these models.

**Comment by skuhl** [comment]
Great! You may also want to confirm that we can get the files that are going to be created for us (or maybe by us?) into this format. Another thing to watch out for is that the units are correct (i.e., it is scaled to the right size and/or uses the right units) and that the origin of the model is where we expect it to be.
