### ISSUE TITLE
Identify list of scenarios

### ISSUE THREAD

**Issue by skuhl** [skuhl/RobotRun#9]
We need to work with Alex/Siddharth to identify what kinds of scenarios we want to be able to load up in the software. Then, we need to prioritize that list and find one that seems both easy to implement and useful from an educational standpoint.

**Comment by skuhl** [comment]
One scenario that seems like a candidate to both easy and useful: Pick up an object with the arm and put it in a box.

**Comment by neoaero99** [comment]
It would seem that all the scenarios involve picking up objects and moving them between areas designated as "fixtures". Though, we may want to include a conveyor belt scenario.

**Comment by neoaero99** [comment]
Siddharth is handling this.
